name: Docker Image CD

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull ankitdocher1/cicd-pipeline:latest
    
    - name: Delete Docker Container
      run: sudo docker rm -f cicd-pipeline-container | true
    
    - name: Run a new Container
      run: sudo docker run -d -p 8081:5000 --name cicd-pipeline-container ankitdocher1/cicd-pipeline
